const countries = [
    { name: "Afghanistan", flag: "🇦🇫" },
    { name: "Åland Islands", flag: "🇦🇽" },
    { name: "Albania", flag: "🇦🇱" },
    { name: "Algeria", flag: "🇩🇿" },
    { name: "American Samoa", flag: "🇦🇸" },
    { name: "Andorra", flag: "🇦🇩" },
    { name: "Angola", flag: "🇦🇴" },
    { name: "Anguilla", flag: "🇦🇮" },
    { name: "Antarctica", flag: "🇦🇶" },
    { name: "Antigua & Barbuda", flag: "🇦🇬" },
    { name: "Argentina", flag: "🇦🇷" },
    { name: "Armenia", flag: "🇦🇲" },
    { name: "Aruba", flag: "🇦🇼" },
    { name: "Australia", flag: "🇦🇺" },
    { name: "Austria", flag: "🇦🇹" },
    { name: "Azerbaijan", flag: "🇦🇿" },
    { name: "Bahamas", flag: "🇧🇸" },
    { name: "Bahrain", flag: "🇧🇭" },
    { name: "Bangladesh", flag: "🇧🇩" },
    { name: "Barbados", flag: "🇧🇧" },
    { name: "Belarus", flag: "🇧🇾" },
    { name: "Belgium", flag: "🇧🇪" },
    { name: "Belize", flag: "🇧🇿" },
    { name: "Benin", flag: "🇧🇯" },
    { name: "Bermuda", flag: "🇧🇲" },
    {name: "Bhutan",flag: "BT"},
    { name: "Bhutan", flag: "🇧🇹" },
    { name: "Bolivia", flag: "🇧🇴" },
    { name: "Caribbean Netherlands", flag: "🇧🇶" },
    { name: "Bosnia & Herzegovina", flag: "🇧🇦" },
    { name: "Botswana", flag: "🇧🇼" },
    { name: "Bouvet Island", flag: "🇧🇻" },
    { name: "Brazil", flag: "🇧🇷" },
    { name: "British Indian Ocean Territory", flag: "🇮🇴" },
    { name: "Brunei", flag: "🇧🇳" },
    { name: "Bulgaria", flag: "🇧🇬" },
    { name: "Burkina Faso", flag: "🇧🇫" },
    { name: "Burundi", flag: "🇧🇮" },
    { name: "Cambodia", flag: "🇰🇭" },
    { name: "Cameroon", flag: "🇨🇲" },
    { name: "Canada", flag: "🇨🇦" },
    { name: "Cape Verde", flag: "🇨🇻" },
    { name: "Cayman Islands", flag: "🇰🇾" },
    { name: "Central African Republic", flag: "🇨🇫" },
    { name: "Chad", flag: "🇹🇩" },
    { name: "Chile", flag: "🇨🇱" },
    { name: "China", flag: "🇨🇳" },
    { name: "Christmas Island", flag: "🇨🇽" },
    { name: "Cocos (Keeling) Islands", flag: "🇨🇨" },
    { name: "Colombia", flag: "🇨🇴" },
    { name: "Comoros", flag: "🇰🇲" },
    { name: "Congo - Brazzaville", flag: "🇨🇬" },
    { name: "Congo - Kinshasa", flag: "🇨🇩" },
    { name: "Cook Islands", flag: "🇨🇰" },
    { name: "Costa Rica", flag: "🇨🇷" },
    { name: "Côte d’Ivoire", flag: "🇨🇮" },
    { name: "Croatia", flag: "🇭🇷" },
    { name: "Cuba", flag: "🇨🇺" },
    { name: "Curaçao", flag: "🇨🇼" },
    { name: "Cyprus", flag: "🇨🇾" },
    { name: "Czechia", flag: "🇨🇿" },
    { name: "Denmark", flag: "🇩🇰" },
    { name: "Djibouti", flag: "🇩🇯" },
    { name: "Dominica", flag: "🇩🇲" },
    { name: "Dominican Republic", flag: "🇩🇴" },
    { name: "Ecuador", flag: "🇪🇨" },
    { name: "Egypt", flag: "🇪🇬" },
    { name: "El Salvador", flag: "🇸🇻" },
    { name: "Equatorial Guinea", flag: "🇬🇶" },
    { name: "Eritrea", flag: "🇪🇷" },
    { name: "Estonia", flag: "🇪🇪" },
    { name: "Ethiopia", flag: "🇪🇹" },
    { name: "Falkland Islands (Islas Malvinas)", flag: "🇫🇰" },
    { name: "Faroe Islands", flag: "🇫🇴" },
    { name: "Fiji", flag: "🇫🇯" },
    { name: "Finland", flag: "🇫🇮" },
    { name: "France", flag: "🇫🇷" },
    { name: "French Guiana", flag: "🇬🇫" },
    { name: "French Polynesia", flag: "🇵🇫" },
    { name: "French Southern Territories", flag: "🇹🇫" },
    { name: "Gabon", flag: "🇬🇦" },
    { name: "Gambia", flag: "🇬🇲" },
    { name: "Georgia", flag: "🇬🇪" },
    { name: "Germany", flag: "🇩🇪" },
    { name: "Ghana", flag: "🇬🇭" },
    { name: "Gibraltar", flag: "🇬🇮" },
    { name: "Greece", flag: "🇬🇷" },
    { name: "Greenland", flag: "🇬🇱" },
    { name: "Grenada", flag: "🇬🇩" },
    { name: "Guadeloupe", flag: "🇬🇵" },
    { name: "Guam", flag: "🇬🇺" },
    { name: "Guatemala", flag: "🇬🇹" },
    { name: "Guernsey", flag: "🇬🇬" },
    { name: "Guinea", flag: "🇬🇳" },
    { name: "Guinea-Bissau", flag: "🇬🇼" },
    { name: "Guyana", flag: "🇬🇾" },
    { name: "Haiti", flag: "🇭🇹" },
    { name: "Heard & McDonald Islands", flag: "🇭🇲" },
    { name: "Vatican City", flag: "🇻🇦" },
    { name: "Honduras", flag: "🇭🇳" },
    { name: "Hong Kong", flag: "🇭🇰" },
    { name: "Hungary", flag: "🇭🇺" },
    { name: "Iceland", flag: "🇮🇸" },
    { name: "India", flag: "🇮🇳" },
    { name: "Indonesia", flag: "🇮🇩" },
    { name: "Iran", flag: "🇮🇷" },
    { name: "Iraq", flag: "🇮🇶" },
    { name: "Ireland", flag: "🇮🇪" },
    { name: "Isle of Man", flag: "🇮🇲" },
    { name: "Israel", flag: "🇮🇱" },
    { name: "Italy", flag: "🇮🇹" },
    { name: "Jamaica", flag: "🇯🇲" },
    { name: "Japan", flag: "🇯🇵" },
    { name: "Jersey", flag: "🇯🇪" },
    { name: "Jordan", flag: "🇯🇴" },
    { name: "Kazakhstan", flag: "🇰🇿" },
    { name: "Kenya", flag: "🇰🇪" },
    { name: "Kiribati", flag: "🇰🇮" },
    { name: "North Korea", flag: "🇰🇵" },
    { name: "South Korea", flag: "🇰🇷" },
    { name: "Kosovo", flag: "🇽🇰" },
    { name: "Kuwait", flag: "🇰🇼" },
    { name: "Kyrgyzstan", flag: "🇰🇬" },
    { name: "Laos", flag: "🇱🇦" },
    { name: "Latvia", flag: "🇱🇻" },
    { name: "Lebanon", flag: "🇱🇧" },
    { name: "Lesotho", flag: "🇱🇸" },
    { name: "Liberia", flag: "🇱🇷" },
    { name: "Libya", flag: "🇱🇾" },
    { name: "Liechtenstein", flag: "🇱🇮" },
    { name: "Lithuania", flag: "🇱🇹" },
    { name: "Luxembourg", flag: "🇱🇺" },
    { name: "Macao", flag: "🇲🇴" },
    { name: "North Macedonia", flag: "🇲🇰" },
    { name: "Madagascar", flag: "🇲🇬" },
    { name: "Malawi", flag: "🇲🇼" },
    { name: "Malaysia", flag: "🇲🇾" },
    { name: "Maldives", flag: "🇲🇻" },
    { name: "Mali", flag: "🇲🇱" },
    { name: "Malta", flag: "🇲🇹" },
    { name: "Marshall Islands", flag: "🇲🇭" },
    { name: "Martinique", flag: "🇲🇶" },
    { name: "Mauritania", flag: "🇲🇷" },
    { name: "Mauritius", flag: "🇲🇺" },
    { name: "Mayotte", flag: "🇾🇹" },
    { name: "Mexico", flag: "🇲🇽" },
    { name: "Micronesia", flag: "🇫🇲" },
    { name: "Moldova", flag: "🇲🇩" },
    { name: "Monaco", flag: "🇲🇨" },
    { name: "Mongolia", flag: "🇲🇳" },
    { name: "Montenegro", flag: "🇲🇪" },
    { name: "Montserrat", flag: "🇲🇸" },
    { name: "Morocco", flag: "🇲🇦" },
    { name: "Mozambique", flag: "🇲🇿" },
    { name: "Myanmar (Burma)", flag: "🇲🇲" },
    { name: "Namibia", flag: "🇳🇦" },
    { name: "Nauru", flag: "🇳🇷" },
    { name: "Nepal", flag: "🇳🇵" },
    { name: "Netherlands", flag: "🇳🇱" },
    { name: "Curaçao", flag: "🇨🇼" },
    { name: "New Caledonia", flag: "🇳🇨" },
    { name: "New Zealand", flag: "🇳🇿" },
    { name: "Nicaragua", flag: "🇳🇮" },
    { name: "Niger", flag: "🇳🇪" },
    { name: "Nigeria", flag: "🇳🇬" },
    { name: "Niue", flag: "🇳🇺" },
    { name: "Norfolk Island", flag: "🇳🇫" },
    { name: "Northern Mariana Islands", flag: "🇲🇵" },
    { name: "Norway", flag: "🇳🇴" },
    { name: "Oman", flag: "🇴🇲" },
    { name: "Pakistan", flag: "🇵🇰" },
    { name: "Palau", flag: "🇵🇼" },
    { name: "Palestine", flag: "🇵🇸" },
    { name: "Panama", flag: "🇵🇦" },
    { name: "Papua New Guinea", flag: "🇵🇬" },
    { name: "Paraguay", flag: "🇵🇾" },
    { name: "Peru", flag: "🇵🇪" },
    { name: "Philippines", flag: "🇵🇭" },
    { name: "Pitcairn Islands", flag: "🇵🇳" },
    { name: "Poland", flag: "🇵🇱" },
    { name: "Portugal", flag: "🇵🇹" },
    { name: "Puerto Rico", flag: "🇵🇷" },
    { name: "Qatar", flag: "🇶🇦" },
    { name: "Réunion", flag: "🇷🇪" },
    { name: "Romania", flag: "🇷🇴" },
    { name: "Russia", flag: "🇷🇺" },
    { name: "Rwanda", flag: "🇷🇼" },
    { name: "St. Barthélemy", flag: "🇧🇱" },
    { name: "St. Helena", flag: "🇸🇭" },
    { name: "St. Kitts & Nevis", flag: "🇰🇳" },
    { name: "St. Lucia", flag: "🇱🇨" },
    { name: "St. Martin", flag: "🇲🇫" },
    { name: "St. Pierre & Miquelon", flag: "🇵🇲" },
    { name: "St. Vincent & Grenadines", flag: "🇻🇨" },
    { name: "Samoa", flag: "🇼🇸" },
    { name: "San Marino", flag: "🇸🇲" },
    { name: "São Tomé & Príncipe", flag: "🇸🇹" },
    { name: "Saudi Arabia", flag: "🇸🇦" },
    { name: "Senegal", flag: "🇸🇳" },
    { name: "Serbia", flag: "🇷🇸" },
    { name: "Seychelles", flag: "🇸🇨" },
    { name: "Sierra Leone", flag: "🇸🇱" },
    { name: "Singapore", flag: "🇸🇬" },
    { name: "Sint Maarten", flag: "🇸🇽" },
    { name: "Slovakia", flag: "🇸🇰" },
    { name: "Slovenia", flag: "🇸🇮" },
    { name: "Solomon Islands", flag: "🇸🇧" },
    { name: "Somalia", flag: "🇸🇴" },
    { name: "South Africa", flag: "🇿🇦" },
    { name: "South Georgia & South Sandwich Islands", flag: "🇬🇸" },
    { name: "South Sudan", flag: "🇸🇸" },
    { name: "Spain", flag: "🇪🇸" },
    { name: "Sri Lanka", flag: "🇱🇰" },
    { name: "Sudan", flag: "🇸🇩" },
    { name: "Suriname", flag: "🇸🇷" },
    { name: "Svalbard & Jan Mayen", flag: "🇸🇯" },
    { name: "Eswatini", flag: "🇸🇿" },
    { name: "Sweden", flag: "🇸🇪" },
    { name: "Switzerland", flag: "🇨🇭" },
    { name: "Syria", flag: "🇸🇾" },
    { name: "Taiwan", flag: "🇹🇼" },
    { name: "Tajikistan", flag: "🇹🇯" },
    { name: "Tanzania", flag: "🇹🇿" },
    { name: "Thailand", flag: "🇹🇭" },
    { name: "Timor-Leste", flag: "🇹🇱" },
    { name: "Togo", flag: "🇹🇬" },
    { name: "Tokelau", flag: "🇹🇰" },
    { name: "Tonga", flag: "🇹🇴" },
    { name: "Trinidad & Tobago", flag: "🇹🇹" },
    { name: "Tunisia", flag: "🇹🇳" },
    { name: "Turkey", flag: "🇹🇷" },
    { name: "Turkmenistan", flag: "🇹🇲" },
    { name: "Turks & Caicos Islands", flag: "🇹🇨" },
    { name: "Tuvalu", flag: "🇹🇻" },
    { name: "Uganda", flag: "🇺🇬" },
    { name: "Ukraine", flag: "🇺🇦" },
    { name: "United Arab Emirates", flag: "🇦🇪" },
    { name: "United Kingdom", flag: "🇬🇧" },
    { name: "United States", flag: "🇺🇸" },
    { name: "U.S. Outlying Islands", flag: "🇺🇲" },
    { name: "Uruguay", flag: "🇺🇾" },
    { name: "Uzbekistan", flag: "🇺🇿" },
    { name: "Vanuatu", flag: "🇻🇺" },
    { name: "Venezuela", flag: "🇻🇪" },
    { name: "Vietnam", flag: "🇻🇳" },
    { name: "British Virgin Islands", flag: "🇻🇬" },
    { name: "U.S. Virgin Islands", flag: "🇻🇮" },
    { name: "Wallis & Futuna", flag: "🇼🇫" },
    { name: "Western Sahara", flag: "🇪🇭" },
    { name: "Yemen", flag: "🇾🇪" },
    { name: "Zambia", flag: "🇿🇲" },
    { name: "Zimbabwe", flag: "🇿🇼" }
];

function getUserCountry() {
    const countryElement = document.querySelector('[itemprop=homeLocation]').querySelector('span');
    const nameElement = document.querySelector('.p-name');
    const foundCountry = countries.find(item => countryElement.innerHTML.includes(item.name));

    if (foundCountry) {
        nameElement.innerHTML += foundCountry.flag;
    }
}

function addArrow() {
    const readme = document.getElementById('user-profile-frame').querySelector(".position-relative").querySelector(".Box").querySelector(".Box-body")
    const content = readme.querySelector(".markdown-body ")
    if (readme) {
        const newElement = document.createElement('div');
        newElement.classList.add('readme-hider__btn')
        newElement.innerHTML = '<svg width="100%" height="100%" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M21.68,17.65l-7-14a3,3,0,0,0-5.36,0l-7,14a3,3,0,0,0,3.9,4.08l5.37-2.4h0a1.06,1.06,0,0,1,.82,0l5.37,2.4a3,3,0,0,0,3.9-4.08Zm-2,2a1,1,0,0,1-1.13.22l-5.37-2.39a3,3,0,0,0-2.44,0L5.41,19.9a1,1,0,0,1-1.3-1.35l7-14a1,1,0,0,1,1.78,0l7,14A1,1,0,0,1,19.72,19.68Z"/></svg>'
        newElement.addEventListener('click', () => {
            newElement.classList.toggle('active')
            if (newElement.classList.contains('active')) {
                readme.style.height = '50px'
                content.style.display = "none"
            } else {
                readme.style.height = 'auto'
                content.style.display = 'block'
            }
        })

        newElement.addEventListener('mouseover', () => {
            newElement.classList.add('hovered')
        })

        newElement.addEventListener('mouseout', () => {
            newElement.classList.remove('hovered')
        })
    
        readme.append(newElement);
    }
}

getUserCountry();
addArrow();